# Generated by Django 3.0.5 on 2020-04-15 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('working', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='verify_link',
        ),
    ]
